### ISSUE TITLE
Abbozzo relazione

### ISSUE THREAD

**Issue by LorenzoMei** [Torkin1/ISPW_project#45]
- 1Software Requirement;
   - 1.Introduction;
      - 1.Aim of the document;
      - 2.Overview of the defined system;
      - 3.Operational settings;
      - 4.Related systems (at least 2), Pros and Cons;
   - 2.User Stories (3 per member);
   - 3.Functional Requirements (3 per member);
   - 4.Use Cases: Overview Diagram (1);
- 2.StoryboardsFormat: HTML Quantity: 2 screens per member, covering all the functionalities described in SRS, developed using Draw.io or similar;
- 3.Design;
   - Activity diagram: 1 per member;
- 5Code
   - Be able to show that Svn(or Git) + Travis + SonarCloud is correctly installed in one of your    computer and it is able to analyze your project for rule violations. No rule must be violated. (link to repo + link to SonarCloud)

**Comment by LorenzoMei** [comment]
[Relazione ISPW.docx](https://github.com/Torkin1/ISPW_project/files/3847057/Relazione.ISPW.docx)

**Comment by Torkin1** [comment]
Add diagrams, links, requirements

**Comment by Torkin1** [comment]
added in revision 36
