### ISSUE TITLE
Rename existing UML classes

### ISSUE THREAD

**Issue by Torkin1** [Torkin1/ISPW_project#61]
Some class names are not conforming to BCE VOPC standards. Follows a list of changes to be applied:
- <\<boundary>> Home ---> <\<boundary>> User_Home;
- <\<boundary>> ViewAds ---> <\<boundary>> User_ViewAnAd;
- <\<boundary>> AnswerAnAd ---> <\<boundary>> User_CheckAnswersRequestAd;
- <\<control>> Request ---> <\<control>> PublishRequest;
- <\<control>> Offer ---> <\<control>> PublishOffert;
- <\<control>> Replies ---> <\<control>> AnswerAnAd;
- <\<control>> Validation ---> <\<control>> ValidateFavor.

PS: Please perform all the tasks specified in this ticket at once (all or nothing policy).

**Comment by mihaiJianu** [comment]
Ticket need to be adjusted, not all of them are correct need more discussion.

**Comment by mihaiJianu** [comment]
Committed on revision 63.
