### ISSUE TITLE
Add missing Entities

### ISSUE THREAD

**Issue by Torkin1** [Torkin1/ISPW_project#65]
According to UC diagram, some entities are missing from the Class Diagram. Follows a list of entities to be implemented:
- <\<entity>> UnemployedUser #80 ;
- <\<entity>> CompanyTalentScout #81;
- <\<entity>> Facebook #82.

**Comment by mihaiJianu** [comment]
Commited on revision 57.

**Comment by Torkin1** [comment]
I'm reopening this issue, so we can use it to keep track of new eniteties to be implemented

**Comment by Torkin1** [comment]
- <\<entity>> ChatRequest #113
- <\<entity>> FavorRequest #
- <\<entity>> OffertApply #
- <\<entity>> PlatformMsg #
- <\<entity>> SentChatRequest #
- <\<entity>> SentFavorRequest # 
- <\<entity>> SentOffertApply #

**Comment by Torkin1** [comment]
nevermind
