### ISSUE TITLE
Add "<<control>> Login"

### ISSUE THREAD

**Issue by Torkin1** [Torkin1/ISPW_project#74]
part of ticket #66

**Comment by mihaiJianu** [comment]
"Facebook" and "Facebook_FacebookLogin" are aggregation on "login" as control, and any class with * has dependecy on login.
Also adjusted some space issues on the diagram and fixed minor distances.
Committed on revision 58.

**Comment by mihaiJianu** [comment]
Should add a description for the "*" near the class names. The description inform that is an assosiaction between login and the "*" class.

**Comment by mihaiJianu** [comment]
Committed on revision 68.
